### ISSUE TITLE
Migrate fails with Activerecord 5.2

### ISSUE THREAD

**Issue by lacostenycoder** [jwo/ActiveRecord-Without-Rails#4]
I was able to get it work with version 4.2 but when tried with 5.2 got error

`NoMethodError: undefined method `migrate' for ActiveRecord::Migrator:Class`

I spent some time to try to get it work but gave up and went with 4.2.

**Comment by lacostenycoder** [comment]
I just went with using the https://github.com/thuss/standalone-migrations and it worked fine with 5.2
